print("Why was the computer cold?")
input("")
print("because it forgot to close its Windows!")
input("---------------------------------")
print("I told my computer I needed a break…")
input("")
print("It said “OK,” and crashed.")
input("-----------------------------------")
print("I asked my smart fridge for a joke.")
input(" ")
print("It said, “I’m too cool for that.”")
input("The End")