print("hello I'am Roddy")
input("")
print("whats your name")
input("")
print("cool nice to meet you")
input("")
print("oh I just forgot I wanted to ask whats your favorite class")
input("")
print("ok...my favorite class is English")
input("")
print("whats your favorite color")
input("")
print("Aight mines Red")
input("")
print("Thank you for filling out my personality quiz...NEXT!")
print("The End")